// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkPdL_uyAWoDeWpVwN3FDt1wV33qlz-FI',
    appId: '1:786149346390:web:05c4aa96ad45d07bb5bff7',
    messagingSenderId: '786149346390',
    projectId: 'my-mynotes-project-34bf0',
    authDomain: 'my-mynotes-project-34bf0.firebaseapp.com',
    storageBucket: 'my-mynotes-project-34bf0.appspot.com',
    measurementId: 'G-3QM9BL8KDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsBL9djlE3dWmY4cu-ugbCio-sVn_sNQ0',
    appId: '1:786149346390:android:cba2bff22eb6e131b5bff7',
    messagingSenderId: '786149346390',
    projectId: 'my-mynotes-project-34bf0',
    storageBucket: 'my-mynotes-project-34bf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvpX_1VFDDecNB4YzIp5mNfJVKz9mBE90',
    appId: '1:786149346390:ios:358c820038b88d80b5bff7',
    messagingSenderId: '786149346390',
    projectId: 'my-mynotes-project-34bf0',
    storageBucket: 'my-mynotes-project-34bf0.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvpX_1VFDDecNB4YzIp5mNfJVKz9mBE90',
    appId: '1:786149346390:ios:358c820038b88d80b5bff7',
    messagingSenderId: '786149346390',
    projectId: 'my-mynotes-project-34bf0',
    storageBucket: 'my-mynotes-project-34bf0.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkPdL_uyAWoDeWpVwN3FDt1wV33qlz-FI',
    appId: '1:786149346390:web:cefdf784095b4e33b5bff7',
    messagingSenderId: '786149346390',
    projectId: 'my-mynotes-project-34bf0',
    authDomain: 'my-mynotes-project-34bf0.firebaseapp.com',
    storageBucket: 'my-mynotes-project-34bf0.appspot.com',
    measurementId: 'G-B3QW66XRJQ',
  );
}
